import 'package:adeline_project_dev/model/user/content/gold_content.dart';
import 'package:flutter/cupertino.dart';

import '../model/icon/iconModel.dart';

List<IconModel> iconList = [
  IconModel('assets/daily/Chaos.png'),
  IconModel('assets/daily/Guardian.png'),
  IconModel('assets/daily/Epona.png'),
  IconModel('assets/week/WeeklyEpona.png'),
  IconModel('assets/week/AbyssDungeon.png'),
  IconModel('assets/expedition/ChallengeAbyss.png'),
  IconModel('assets/week/AbyssRaid.png'),
  IconModel('assets/week/Crops.png'),
  IconModel('assets/expedition/ChaosGate.png'),
  IconModel('assets/expedition/GhostShip.png'),
  IconModel('assets/expedition/Rehearsal.png'),
  IconModel('assets/expedition/Dejavu.png'),
  IconModel('assets/etc/GuildCoin.png'),
  IconModel('assets/etc/PirateCoin.png'),
  IconModel('assets/expedition/Dungeon.png'),
  IconModel('assets/etc/QuestNormal.png'),
  IconModel('assets/etc/SubjugationBattle.png'),
  IconModel('assets/expedition/ExpeditionFarm.png'),
  IconModel('assets/expedition/LifeEnergy.png'),
  IconModel('assets/expedition/LikeAbility.png'),
  IconModel('assets/expedition/PlatinumField.png'),
  IconModel('assets/etc/Cube.png'),
  IconModel('assets/etc/BossRush.png'),
  IconModel('assets/etc/Ticket.png'),
];
final List<GoldContent> constGoldContents = [
  GoldContent(
    type: "어비스 던전",
    name: "오레하의 우물",
    difficulty: "노말",
    totalPhase: 2,
    enterLevelLimit: 1325,
    levelLimitPerPhase: [1325, 1325],
    goldPerPhase: [1100],
    getGoldLevelLimit: 1415,
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "어비스 던전",
    name: "오레하의 우물",
    difficulty: "하드",
    totalPhase: 2,
    enterLevelLimit: 1325,
    levelLimitPerPhase: [1325, 1325],
    getGoldLevelLimit: 1415,
    goldPerPhase: [1300],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "어비스 레이드",
    name: "아르고스",
    difficulty: "",
    totalPhase: 3,
    enterLevelLimit: 1370,
    levelLimitPerPhase: [1370, 1385, 1400],
    getGoldLevelLimit: 1475,
    goldPerPhase: [700, 400, 500],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "군단장",
    name: "발탄",
    difficulty: "노말",
    totalPhase: 2,
    enterLevelLimit: 1415,
    levelLimitPerPhase: [1415, 1415],
    getGoldLevelLimit: 9999,
    goldPerPhase: [500, 2000],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "군단장",
    name: "발탄",
    difficulty: "하드",
    totalPhase: 2,
    enterLevelLimit: 1445,
    levelLimitPerPhase: [1445, 1445],
    getGoldLevelLimit: 9999,
    goldPerPhase: [1000, 3500],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "군단장",
    name: "비아키스",
    difficulty: "노말",
    totalPhase: 3,
    enterLevelLimit: 1430,
    levelLimitPerPhase: [1430, 1430, 1430],
    getGoldLevelLimit: 9999,
    goldPerPhase: [500, 2000],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "군단장",
    name: "비아키스",
    difficulty: "하드",
    totalPhase: 3,
    enterLevelLimit: 1460,
    levelLimitPerPhase: [1460, 1460, 1460],
    getGoldLevelLimit: 9999,
    goldPerPhase: [1000, 1000, 2500],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "군단장",
    name: "쿠크세이튼",
    difficulty: "노말",
    totalPhase: 3,
    enterLevelLimit: 1475,
    levelLimitPerPhase: [1475, 1475, 1475],
    getGoldLevelLimit: 9999,
    goldPerPhase: [1000, 1000, 2500],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "군단장",
    name: "아브렐슈드",
    difficulty: "노말",
    totalPhase: 6,
    enterLevelLimit: 1490,
    levelLimitPerPhase: [1490, 1490, 1500, 1500, 1520, 1520],
    getGoldLevelLimit: 9999,
    goldPerPhase: [2000, 2500, 700, 800, 1000, 1500],
    clearGold: 0,
    characterAlwaysMaxClear: false,
  ),
  GoldContent(
    type: "군단장",
    name: "아브렐슈드",
    difficulty: "하드",
    totalPhase: 6,
    enterLevelLimit: 1540,
    levelLimitPerPhase: [1540, 1540, 1550, 1550, 1560, 1560],
    getGoldLevelLimit: 9999,
    goldPerPhase: [2500, 3000, 900, 1100, 1200, 1800],
    clearGold: 0,
    characterAlwaysMaxClear: false,
  ),
];

Map<String, Map<String, int>> merchantMapOfMap = {
  '아르테미스': {
    '로그힐': 1,
    '안게모스 산 기슭': 2,
    '국경지대': 3,
  },
  '유디아': {
    '살란드 구릉지': 4,
    '오즈혼 구릉지': 5,
  },
  '루테란 서부': {
    '자고라스 산': 6,
    '레이크바': 7,
    '메드리닉 수도원': 8,
    '빌브린 숲': 9,
    '격전의 평야': 10,
  },
  '루테란 동부': {
    '디오리카 평원': 11,
    '해무리 언덕': 12,
    '배꽃나무 자생지': 13,
    '흑장미 교회당': 14,
    '라니아 단구': 15,
    '보레아 영지': 16,
    '크로커니스 해변': 17,
  },
  '토토이크': {
    '바다향기 숲': 18,
    '달콤한 숲': 19,
    '성큼바위 숲': 20,
    '침묵하는 거인의 숲': 21,
  },
  '애니츠': {
    '델파이 현': 22,
    '등나무 언덕': 23,
    '소리의 숲': 24,
    '거울 계곡': 25,
    '황혼의 연무': 26,
  },
  '아르데타인': {
    '메마른 통로': 27,
    '갈라진 땅': 28,
    '네벨호른': 29,
    '바람결 구릉지': 30,
    '토트리치': 31,
    '리제 폭포': 32,
  },
  '베른 북부': {
    '크로나 항구': 33,
    '파르나 숲': 34,
    '페스나르 고원': 35,
    '베르닐 삼림': 36,
    '발란카르 산맥': 37,
  },
  '슈샤이어': {
    '얼어붙은 바다': 38,
    '칼날바람 언덕': 39,
    '서리감옥 고원': 40,
    '머무른 시간의 호수': 41,
    '얼음나비 절벽': 42,
  },
  '로헨델': {
    '은빛물결 호수': 43,
    '유리연꽃 호수': 44,
    '바람향기 언덕': 45,
    '파괴된 제나일': 46,
    '엘조윈의 그늘': 47,
  },
  '욘': {
    '시작의 땅': 48,
    '미완의 정원': 49,
    '검은모루 작업장': 50,
    '무쇠망치 작업장': 51,
    '기약의 땅': 52,
  },
  '페이튼': {
    '칼라자 마을': 53,
  },
  '파푸니카': {
    '얕은 바닷길': 54,
    '별모래 해변': 55,
    '티카티카 군락지': 56,
    '비밀의 숲': 57,
  },
  '베른 남부': {
    '칸다리아 영지': 58,
    '벨리온 유적지': 59,
  },
  '로웬': {
    '어금니의 강': 60,
    '웅크린 늑대의 땅': 61,
  },
};
Map<String, int> merchantMap = {
  '로그힐': 1,
  '안게모스 산 기슭': 2,
  '국경지대': 3,
  '살란드 구릉지': 4,
  '오즈혼 구릉지': 5,
  '자고라스 산': 6,
  '레이크바': 7,
  '메드리닉 수도원': 8,
  '빌브린 숲': 9,
  '격전의 평야': 10,
  '디오리카 평원': 11,
  '해무리 언덕': 12,
  '배꽃나무 자생지': 13,
  '흑장미 교회당': 14,
  '라니아 단구': 15,
  '보레아 영지': 16,
  '크로커니스 해변': 17,
  '바다향기 숲': 18,
  '달콤한 숲': 19,
  '성큼바위 숲': 20,
  '침묵하는 거인의 숲': 21,
  '델파이 현': 22,
  '등나무 언덕': 23,
  '소리의 숲': 24,
  '거울 계곡': 25,
  '황혼의 연무': 26,
  '메마른 통로': 27,
  '갈라진 땅': 28,
  '네벨호른': 29,
  '바람결 구릉지': 30,
  '토트리치': 31,
  '리제 폭포': 32,
  '크로나 항구': 33,
  '파르나 숲': 34,
  '페스나르 고원': 35,
  '베르닐 삼림': 36,
  '발란카르 산맥': 37,
  '얼어붙은 바다': 38,
  '칼날바람 언덕': 39,
  '서리감옥 고원': 40,
  '머무른 시간의 호수': 41,
  '얼음나비 절벽': 42,
  '은빛물결 호수': 43,
  '유리연꽃 호수': 44,
  '바람향기 언덕': 45,
  '파괴된 제나일': 46,
  '엘조윈의 그늘': 47,
  '시작의 땅': 48,
  '미완의 정원': 49,
  '검은모루 작업장': 50,
  '무쇠망치 작업장': 51,
  '기약의 땅': 52,
  '칼라자 마을': 53,
  '얕은 바닷길': 54,
  '별모래 해변': 55,
  '티카티카 군락지': 56,
  '비밀의 숲': 57,
  '칸다리아 영지': 58,
  '벨리온 유적지': 59,
  '어금니의 강': 60,
  '웅크린 늑대의 땅': 61,
};

List<String> serverList = [
  "루페온",
  "실리안",
  "아만",
  "카마인",
  "카제로스",
  "아브렐슈드",
  "카단",
  "니나브",
];

List<String> jobList = [
  "버서커",
  "디스트로이어",
  "워로드",
  "홀리나이트",
  "아르카나",
  "서머너",
  "바드",
  "소서리스",
  "배틀마스터",
  "인파이터",
  "기공사",
  "창술사",
  "스트라이커",
  "데모닉",
  "블레이드",
  "리퍼",
  "호크아이",
  "데빌헌터",
  "블래스터",
  "스카우터",
  "건슬링어",
  "도화가",
];
