import 'package:adeline_project_dev/model/user/content/gold_content.dart';
import 'package:flutter/cupertino.dart';

ValueNotifier<int> valTanNormal = ValueNotifier<int>(0);
ValueNotifier<int> valTanHard = ValueNotifier<int>(0);
ValueNotifier<int> biacKissNormal = ValueNotifier<int>(0);
ValueNotifier<int> biacKissHard = ValueNotifier<int>(0);
ValueNotifier<int> koukoSatonNormal = ValueNotifier<int>(0);
ValueNotifier<int> abrelshudNormal = ValueNotifier<int>(0);
ValueNotifier<int> abrelshudHard = ValueNotifier<int>(0);
ValueNotifier<int> orehaNormal = ValueNotifier<int>(0);
ValueNotifier<int> orehaHard = ValueNotifier<int>(0);
ValueNotifier<int> argus = ValueNotifier<int>(0);

final List<GoldContent> constGoldContents = [
  GoldContent(
    type: "어비스 던전",
    name: "오레하의 우물",
    difficulty: "노말",
    totalPhase: 2,
    enterLevelLimit: 1325,
    levelLimitPerPhase: [1325, 1325],
    goldPerPhase: [1100],
    getGoldLevelLimit: 1415,
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "어비스 던전",
    name: "오레하의 우물",
    difficulty: "하드",
    totalPhase: 2,
    enterLevelLimit: 1325,
    levelLimitPerPhase: [1325, 1325],
    getGoldLevelLimit: 1415,
    goldPerPhase: [1300],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "어비스 레이드",
    name: "아르고스",
    difficulty: "",
    totalPhase: 3,
    enterLevelLimit: 1370,
    levelLimitPerPhase: [1370, 1385, 1415],
    getGoldLevelLimit: 1475,
    goldPerPhase: [700, 400, 500],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "군단장",
    name: "발탄",
    difficulty: "노말",
    totalPhase: 2,
    enterLevelLimit: 1415,
    levelLimitPerPhase: [1415, 1415],
    getGoldLevelLimit: 9999,
    goldPerPhase: [500, 2000],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "군단장",
    name: "발탄",
    difficulty: "하드",
    totalPhase: 2,
    enterLevelLimit: 1445,
    levelLimitPerPhase: [1445, 1445],
    getGoldLevelLimit: 9999,
    goldPerPhase: [1000, 3500],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "군단장",
    name: "비아키스",
    difficulty: "노말",
    totalPhase: 3,
    enterLevelLimit: 1430,
    levelLimitPerPhase: [1430, 1430, 1430],
    getGoldLevelLimit: 9999,
    goldPerPhase: [500, 2000],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "군단장",
    name: "비아키스",
    difficulty: "하드",
    totalPhase: 3,
    enterLevelLimit: 1460,
    levelLimitPerPhase: [1460, 1460, 1460],
    getGoldLevelLimit: 9999,
    goldPerPhase: [1000, 1000, 2500],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "군단장",
    name: "쿠크세이튼",
    difficulty: "노말",
    totalPhase: 3,
    enterLevelLimit: 1475,
    levelLimitPerPhase: [1475, 1475, 1475],
    getGoldLevelLimit: 9999,
    goldPerPhase: [1000, 1000, 2500],
    clearGold: 0,
    characterAlwaysMaxClear: true,
  ),
  GoldContent(
    type: "군단장",
    name: "아브렐슈드",
    difficulty: "노말",
    totalPhase: 6,
    enterLevelLimit: 1490,
    levelLimitPerPhase: [1490, 1490, 1500, 1500, 1520, 1520],
    getGoldLevelLimit: 9999,
    goldPerPhase: [2000, 2500, 700, 800, 1000, 1500],
    clearGold: 0,
    characterAlwaysMaxClear: false,
  ),
  GoldContent(
    type: "군단장",
    name: "아브렐슈드",
    difficulty: "하드",
    totalPhase: 6,
    enterLevelLimit: 1540,
    levelLimitPerPhase: [1540, 1540, 1550, 1550, 1560, 1560],
    getGoldLevelLimit: 9999,
    goldPerPhase: [2500, 3000, 900, 1100, 1200, 1800],
    clearGold: 0,
    characterAlwaysMaxClear: false,
  ),
];
