import 'package:adeline_app/model/user/content/raid_content.dart';

import '../model/icon/iconModel.dart';

List<IconModel> iconList = [
  IconModel('assets/daily/0.png'),
  IconModel('assets/daily/1.png'),
  IconModel('assets/daily/2.png'),
  IconModel('assets/week/WeeklyEpona.png'),
  IconModel('assets/week/AbyssDungeon.png'),
  IconModel('assets/expedition/ChallengeAbyss.png'),
  IconModel('assets/week/AbyssRaid.png'),
  IconModel('assets/week/Crops.png'),
  IconModel('assets/expedition/ChaosGate.png'),
  IconModel('assets/expedition/GhostShip.png'),
  IconModel('assets/expedition/Rehearsal.png'),
  IconModel('assets/expedition/Dejavu.png'),
  IconModel('assets/etc/GuildCoin.png'),
  IconModel('assets/etc/PirateCoin.png'),
  IconModel('assets/expedition/Dungeon.png'),
  IconModel('assets/etc/QuestNormal.png'),
  IconModel('assets/etc/SubjugationBattle.png'),
  IconModel('assets/expedition/ExpeditionFarm.png'),
  IconModel('assets/expedition/LifeEnergy.png'),
  IconModel('assets/expedition/LikeAbility.png'),
  IconModel('assets/expedition/PlatinumField.png'),
  IconModel('assets/expedition/EponaCoin.png'),
  IconModel('assets/etc/Cube.png'),
  IconModel('assets/etc/BossRush.png'),
  IconModel('assets/etc/Ticket.png'),
  IconModel('assets/etc/길드명예훈장.png'),
  IconModel('assets/etc/길드출석.png'),
  IconModel('assets/etc/메인퀘스트.png'),
  IconModel('assets/etc/에스더.webp'),
  IconModel('assets/etc/월드퀘스트.png'),
  IconModel('assets/etc/주간길드.png'),
  IconModel('assets/etc/카게지도.png'),
  IconModel('assets/etc/큐브하드.webp'),
  IconModel('assets/etc/협동퀘스트.png'),
  IconModel('assets/etc/회랑티켓헬.webp'),
  IconModel('assets/etc/회랑하드.webp'),
  IconModel('assets/etc/베아트리스의축복.png'),
  IconModel('assets/etc/니나브의축복.webp'),
  IconModel('assets/etc/비탄의섬.png'),
];
final List<RaidContent> constRaidContents = [
  RaidContent(
    type: "군단장",
    name: "발탄",
    getGoldLevelLimit: 9999,
    clearGold: 0,
    clearCheckStandardPhase: 2,
    totalPhase: 2,
    difficulty: ['노말', '하드'],
    reward: {
      '노말': {
        '클리어골드': [500, 2000], // 2500
        '더보기골드': [500, 800], // 1300, 2500 - 1300 = 1200
        '입장레벨제한': 1415,
        '골드획득레벨제한': 9999,
      },
      '하드': {
        '클리어골드': [1000, 3500], // 4500
        '더보기골드': [900, 1200], // 2100 , 4500 - 2100 = 2400
        '입장레벨제한': 1445,
        '골드획득레벨제한': 9999,
      }
    },
    clearList: [],
    bonusList: [],
  ),
  RaidContent(
    type: "군단장",
    name: "비아키스",
    getGoldLevelLimit: 9999,
    clearGold: 0,
    clearCheckStandardPhase: 3,
    totalPhase: 3,
    difficulty: ['노말', '하드'],
    reward: {
      '노말': {
        '클리어골드': [500, 600, 1400],
        '더보기골드': [400, 600, 800],
        '입장레벨제한': 1430,
        '골드획득레벨제한': 9999,
      },
      '하드': {
        '클리어골드': [1000, 1000, 2500],
        '더보기골드': [700, 900, 1200],
        '입장레벨제한': 1460,
        '골드획득레벨제한': 9999,
      }
    },
    clearList: [],
    bonusList: [],
  ),
  RaidContent(
    type: "군단장",
    name: "쿠크세이튼",
    getGoldLevelLimit: 9999,
    clearGold: 0,
    clearCheckStandardPhase: 3,
    totalPhase: 3,
    difficulty: ['노말'],
    reward: {
      '노말': {
        '클리어골드': [1000, 1000, 2500],
        '더보기골드': [800, 1000, 1300],
        '입장레벨제한': 1475,
        '골드획득레벨제한': 9999,
      }
    },
    clearList: [],
    bonusList: [],
  ),
  RaidContent(
    type: "군단장",
    name: "아브렐슈드",
    getGoldLevelLimit: 9999,
    // 골드획득제한을 걸어두는 이유는 아르고스나 오레하 같이 기사는 골드획득을 하지 못하는 대신 버스비를 받고 추가 골드에 체크할수 있기때문에 남겨두는 것
    clearGold: 0,
    clearCheckStandardPhase: 6,
    totalPhase: 6,
    difficulty: ['노말', '하드'],
    reward: {
      '노말': {
        '클리어골드': [2000, 2500, 700, 800, 1000, 1500],
        '더보기골드': [400, 600, 700, 800, 900, 1100],
        '입장레벨제한': 1490,
        '골드획득레벨제한': 9999,
      },
      '하드': {
        '클리어골드': [2500, 3000, 900, 1100, 1200, 1800],
        '더보기골드': [700, 800, 900, 1100, 1100, 1400],
        '입장레벨제한': 1540,
        '골드획득레벨제한': 9999,
      },
    },
    clearList: [],
    bonusList: [],
  ),
  RaidContent(
    type: "아르고스",
    name: "아르고스",
    getGoldLevelLimit: 1475,
    // 골드획득제한을 걸어두는 이유는 아르고스나 오레하 같이 기사는 골드획득을 하지 못하는 대신 버스비를 받고 추가 골드에 체크할수 있기때문에 남겨두는 것
    clearGold: 0,
    clearCheckStandardPhase: 3,
    totalPhase: 3,
    difficulty: ['일반'],
    reward: {
      '일반': {
        '클리어골드': [700,400,500],
        '더보기골드': [0,0,500],
        '입장레벨제한': 9999,
        '골드획득레벨제한': 1475,
      },
    },
    clearList: [],
    bonusList: [],
  ),
  RaidContent(
    type: "오레하",
    name: "아이라의 눈",
    getGoldLevelLimit: 1415,
    // 골드획득제한을 걸어두는 이유는 아르고스나 오레하 같이 기사는 골드획득을 하지 못하는 대신 버스비를 받고 추가 골드에 체크할수 있기때문에 남겨두는 것
    clearGold: 0,
    clearCheckStandardPhase: 1,
    totalPhase: 1,
    difficulty: ['노말','하드'],
    reward: {
      '노말': {
        '클리어골드': [500],
        '더보기골드': [200],
        '입장레벨제한': 9999,
        '골드획득레벨제한': 1415,
      },
      '하드': {
        '클리어골드': [600],
        '더보기골드': [300],
        '입장레벨제한': 9999,
        '골드획득레벨제한': 1415,
      },
    },
    clearList: [],
    bonusList: [],
  ),
  RaidContent(
    type: "오레하",
    name: "오레하 프라바사",
    getGoldLevelLimit: 1415,
    // 골드획득제한을 걸어두는 이유는 아르고스나 오레하 같이 기사는 골드획득을 하지 못하는 대신 버스비를 받고 추가 골드에 체크할수 있기때문에 남겨두는 것
    clearGold: 0,
    clearCheckStandardPhase: 1,
    totalPhase: 1,
    difficulty: ['노말','하드'],
    reward: {
      '노말': {
        '클리어골드': [600],
        '더보기골드': [400],
        '입장레벨제한': 9999,
        '골드획득레벨제한': 1415,
      },
      '하드': {
        '클리어골드': [700],
        '더보기골드': [500],
        '입장레벨제한': 9999,
        '골드획득레벨제한': 1415,
      },
    },
    clearList: [],
    bonusList: [],
  ),
  RaidContent(
    type: "카양겔",
    name: "천공의 문 넬라시아",
    getGoldLevelLimit: 9999,
    // 골드획득제한을 걸어두는 이유는 아르고스나 오레하 같이 기사는 골드획득을 하지 못하는 대신 버스비를 받고 추가 골드에 체크할수 있기때문에 남겨두는 것
    clearGold: 0,
    clearCheckStandardPhase: 1,
    totalPhase: 1,
    difficulty: ['노말','하드1','하드2','하드3'],
    reward: {
      '노말': {
        '클리어골드': [0],
        '더보기골드': [400],
        '입장레벨제한': 1475,
        '골드획득레벨제한': 9999,
      },
      '하드1': {
        '클리어골드': [0],
        '더보기골드': [700],
        '입장레벨제한': 1520,
        '골드획득레벨제한': 9999,
      },
      '하드2': {
        '클리어골드': [0],
        '더보기골드': [900],
        '입장레벨제한': 1560,
        '골드획득레벨제한': 9999,
      },
      '하드3': {
        '클리어골드': [0],
        '더보기골드': [1100],
        '입장레벨제한': 1580,
        '골드획득레벨제한': 9999,
      },
    },
    clearList: [],
    bonusList: [],
  ),
  RaidContent(
    type: "카양겔",
    name: "영원한 빛의 요람",
    getGoldLevelLimit: 9999,
    // 골드획득제한을 걸어두는 이유는 아르고스나 오레하 같이 기사는 골드획득을 하지 못하는 대신 버스비를 받고 추가 골드에 체크할수 있기때문에 남겨두는 것
    clearGold: 0,
    clearCheckStandardPhase: 1,
    totalPhase: 1,
    difficulty: ['노말','하드1','하드2','하드3'],
    reward: {
      '노말': {
        '클리어골드': [0],
        '더보기골드': [600],
        '입장레벨제한': 1475,
        '골드획득레벨제한': 9999,
      },
      '하드1': {
        '클리어골드': [0],
        '더보기골드': [800],
        '입장레벨제한': 1520,
        '골드획득레벨제한': 9999,
      },
      '하드2': {
        '클리어골드': [0],
        '더보기골드': [1100],
        '입장레벨제한': 1560,
        '골드획득레벨제한': 9999,
      },
      '하드3': {
        '클리어골드': [0],
        '더보기골드': [1400],
        '입장레벨제한': 1580,
        '골드획득레벨제한': 9999,
      },
    },
    clearList: [],
    bonusList: [],
  ),
];

Map<String, Map<String, int>> merchantMapOfMap = {
  '아르테미스': {
    '로그힐': 1,
    '안게모스 산 기슭': 2,
    '국경지대': 3,
  },
  '유디아': {
    '살란드 구릉지': 4,
    '오즈혼 구릉지': 5,
  },
  '루테란 서부': {
    '자고라스 산': 6,
    '레이크바': 7,
    '메드리닉 수도원': 8,
    '빌브린 숲': 9,
    '격전의 평야': 10,
  },
  '루테란 동부': {
    '디오리카 평원': 11,
    '해무리 언덕': 12,
    '배꽃나무 자생지': 13,
    '흑장미 교회당': 14,
    '라니아 단구': 15,
    '보레아 영지': 16,
    '크로커니스 해변': 17,
  },
  '토토이크': {
    '바다향기 숲': 18,
    '달콤한 숲': 19,
    '성큼바위 숲': 20,
    '침묵하는 거인의 숲': 21,
  },
  '애니츠': {
    '델파이 현': 22,
    '등나무 언덕': 23,
    '소리의 숲': 24,
    '거울 계곡': 25,
    '황혼의 연무': 26,
  },
  '아르데타인': {
    '메마른 통로': 27,
    '갈라진 땅': 28,
    '네벨호른': 29,
    '바람결 구릉지': 30,
    '토트리치': 31,
    '리제 폭포': 32,
  },
  '베른 북부': {
    '크로나 항구': 33,
    '파르나 숲': 34,
    '페스나르 고원': 35,
    '베르닐 삼림': 36,
    '발란카르 산맥': 37,
  },
  '슈샤이어': {
    '얼어붙은 바다': 38,
    '칼날바람 언덕': 39,
    '서리감옥 고원': 40,
    '머무른 시간의 호수': 41,
    '얼음나비 절벽': 42,
  },
  '로헨델': {
    '은빛물결 호수': 43,
    '유리연꽃 호수': 44,
    '바람향기 언덕': 45,
    '파괴된 제나일': 46,
    '엘조윈의 그늘': 47,
  },
  '욘': {
    '시작의 땅': 48,
    '미완의 정원': 49,
    '검은모루 작업장': 50,
    '무쇠망치 작업장': 51,
    '기약의 땅': 52,
  },
  '페이튼': {
    '칼라자 마을': 53,
  },
  '파푸니카': {
    '얕은 바닷길': 54,
    '별모래 해변': 55,
    '티카티카 군락지': 56,
    '비밀의 숲': 57,
  },
  '베른 남부': {
    '칸다리아 영지': 58,
    '벨리온 유적지': 59,
  },
  '로웬': {
    '어금니의 강': 60,
    '웅크린 늑대의 땅': 61,
  },
};
Map<String, int> merchantMap = {
  '로그힐': 1,
  '안게모스 산 기슭': 2,
  '국경지대': 3,
  '살란드 구릉지': 4,
  '오즈혼 구릉지': 5,
  '자고라스 산': 6,
  '레이크바': 7,
  '메드리닉 수도원': 8,
  '빌브린 숲': 9,
  '격전의 평야': 10,
  '디오리카 평원': 11,
  '해무리 언덕': 12,
  '배꽃나무 자생지': 13,
  '흑장미 교회당': 14,
  '라니아 단구': 15,
  '보레아 영지': 16,
  '크로커니스 해변': 17,
  '바다향기 숲': 18,
  '달콤한 숲': 19,
  '성큼바위 숲': 20,
  '침묵하는 거인의 숲': 21,
  '델파이 현': 22,
  '등나무 언덕': 23,
  '소리의 숲': 24,
  '거울 계곡': 25,
  '황혼의 연무': 26,
  '메마른 통로': 27,
  '갈라진 땅': 28,
  '네벨호른': 29,
  '바람결 구릉지': 30,
  '토트리치': 31,
  '리제 폭포': 32,
  '크로나 항구': 33,
  '파르나 숲': 34,
  '페스나르 고원': 35,
  '베르닐 삼림': 36,
  '발란카르 산맥': 37,
  '얼어붙은 바다': 38,
  '칼날바람 언덕': 39,
  '서리감옥 고원': 40,
  '머무른 시간의 호수': 41,
  '얼음나비 절벽': 42,
  '은빛물결 호수': 43,
  '유리연꽃 호수': 44,
  '바람향기 언덕': 45,
  '파괴된 제나일': 46,
  '엘조윈의 그늘': 47,
  '시작의 땅': 48,
  '미완의 정원': 49,
  '검은모루 작업장': 50,
  '무쇠망치 작업장': 51,
  '기약의 땅': 52,
  '칼라자 마을': 53,
  '얕은 바닷길': 54,
  '별모래 해변': 55,
  '티카티카 군락지': 56,
  '비밀의 숲': 57,
  '칸다리아 영지': 58,
  '벨리온 유적지': 59,
  '어금니의 강': 60,
  '웅크린 늑대의 땅': 61,
};

List<String> serverList = [
  "루페온",
  "실리안",
  "아만",
  "카마인",
  "카제로스",
  "아브렐슈드",
  "카단",
  "니나브",
];

List<String> jobList = [
  "버서커",
  "디스트로이어",
  "워로드",
  "홀리나이트",
  "아르카나",
  "서머너",
  "바드",
  "소서리스",
  "배틀마스터",
  "인파이터",
  "기공사",
  "창술사",
  "스트라이커",
  "데모닉",
  "블레이드",
  "리퍼",
  "호크아이",
  "데빌헌터",
  "블래스터",
  "스카우터",
  "건슬링어",
  "도화가",
];
