// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa2MQ9Dg-hSvN9jB7w3dkbCOV-ijo86N8',
    appId: '1:939556178498:web:3b6d9bc0480b64baadfbdb',
    messagingSenderId: '939556178498',
    projectId: 'lostark-adeline-app',
    authDomain: 'lostark-adeline-app.firebaseapp.com',
    storageBucket: 'lostark-adeline-app.appspot.com',
    measurementId: 'G-GYKLB6HRF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkiBnCd0J6j8_nxl1Z4p6gNmFT9WDJ9AU',
    appId: '1:939556178498:android:f4bbdb358629c9b1adfbdb',
    messagingSenderId: '939556178498',
    projectId: 'lostark-adeline-app',
    storageBucket: 'lostark-adeline-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1OUaJmzcghUdwVxUEp1MR4pVa_dPp668',
    appId: '1:939556178498:ios:3d5d13db3ad0155eadfbdb',
    messagingSenderId: '939556178498',
    projectId: 'lostark-adeline-app',
    storageBucket: 'lostark-adeline-app.appspot.com',
    iosClientId: '939556178498-89opa3dr4jese5cfbakpisc14rfvc59r.apps.googleusercontent.com',
    iosBundleId: 'com.example.adelineProjectDev',
  );
}
